<?php

/**
 * Question
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    webmontag
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Question extends BaseQuestion
{
  protected function getBaseTag()
  {
    return sprintf('#wbmle%d', $this->id);
  }

  public function getYesTag()
  {
    return $this->getBaseTag() . 'y';
  }

  public function getNoTag()
  {
    return $this->getBaseTag() . 'n';
  }
}
